apiVersion: v1
kind: Service
metadata:
  name: multiplication-service
  labels:
    app: calculator
    service: multiplication
spec:
  selector:
    app: calculator
    service: multiplication
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP
