apiVersion: v1
kind: Service
metadata:
  name: parser-service
  labels:
    app: calculator
    service: parser
spec:
  selector:
    app: calculator
    service: parser
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
