apiVersion: v1
kind: Service
metadata:
  name: subtraction-service
  labels:
    app: calculator
    service: subtraction
spec:
  selector:
    app: calculator
    service: subtraction
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
