apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: calculator
    service: gateway
spec:
  selector:
    app: calculator
    service: gateway
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
