{{- if .Values.parser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.parser.name }}
  labels:
    {{- include "calculator.serviceLabels" (dict "context" . "serviceName" "parser") | nindent 4 }}
spec:
  selector:
    {{- include "calculator.serviceSelectorLabels" (dict "serviceName" "parser") | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.parser.service.port }}
    targetPort: {{ .Values.parser.service.targetPort }}
    protocol: TCP
  type: {{ .Values.parser.service.type }}
{{- end }}
